apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditrisk-fe
  labels:
    app: creditrisk-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creditrisk-fe
  template:
    metadata:
      labels:
        app: creditrisk-fe
    spec:
      containers:
      - name: nginx
        image: khairulhabib/creditrisk-fe:0.1.0
        ports:
        - containerPort: 8080
        env:
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: creditrisk-properties
                key: BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: creditrisk-fe-service
spec:
  selector:
    app: creditrisk-fe
  ports:
    - protocol: TCP
      port: 8080

          